# Generated by Django 3.1.3 on 2020-11-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_type',
            new_name='GameType',
        ),
    ]
